language: go
sudo: required

go:
    - 1.7
    - tip

env:
    - COVERALLS_TOKEN=zstmJAjtUJNpNu4QtWYwRmmjPYu3Iubi5

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/pierrre/gotestcover
  - go get github.com/fzipp/gocyclo
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/golang/lint/golint
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/01org/ciao/test-cases

script:
   - go env
   - go list ./... | xargs -t misspell
   - go list ./... | xargs -t go vet
   - if [[ "$TRAVIS_GO_VERSION" != "tip" ]] ; then go list ./... | xargs -tL 1 golint -set_exit_status ; fi
   - go list ./... | xargs go list -f '{{.Dir}}/*.go' | xargs -I % bash -c "misspell -error %"
   - go list ./... | xargs go list -f '{{.Dir}}' | xargs gocyclo -over 15
   - go list ./... | xargs go list -f '{{.Dir}}' | xargs -L 1 ineffassign
   - go list ./... | xargs go list -f '{{.Dir}}' | xargs gofmt -s -l | wc -l | xargs -I % bash -c "test % -eq 0"
   - go build ./...
   - export GOROOT=`go env GOROOT` && sudo -E PATH=$PATH:$GOROOT/bin $GOPATH/bin/test-cases -v -timeout 9 -short -coverprofile /tmp/cover.out github.com/containers/virtcontainers/...

after_success:
   - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=/tmp/cover.out
